server:
  port: 8081

spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:mysql://localhost:3306/inventorydb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # dev only.Ensure Hibernate is set to create/update the schema
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  sql:
    init:
      mode: never   # IMPORTANT â†’ we control data via API

#Retry Config
resilience4j:
  retry:
    instances:
      inventoryRetry:
        max-attempts: 3
        wait-duration: 100ms
        retry-exceptions:
          - jakarta.persistence.OptimisticLockException
#            # Retry for almost everything
  #            retry-exceptions:
  #              - java.lang.Exception
  #            # Explicitly skip these
  #            ignore-exceptions:
  #              - com.example.exceptions.BusinessValidationException
  #              - jakarta.persistence.EntityNotFoundException

  circuitbreaker:
    instances:
      inventoryCB:
        failure-rate-threshold: 50
        sliding-window-size: 10
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,retries,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always
