server:
  port: 8081

spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:h2:mem:inventorydb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    defer-datasource-initialization: true # Force data.sql to wait until JPA has created the tables
    hibernate:
      ddl-auto: update # Ensure Hibernate is set to create/update the schema
    show-sql: true

  # 1. Enable the console
  h2:
    console:
      enabled: true
      path: /h2-console  # Spring boot 4+ is not working with H2

#Retry Config
resilience4j:
  retry:
    instances:
      inventoryRetry:
        max-attempts: 3
        wait-duration: 100ms
        retry-exceptions:
          - jakarta.persistence.OptimisticLockException
#            # Retry for almost everything
  #            retry-exceptions:
  #              - java.lang.Exception
  #            # Explicitly skip these
  #            ignore-exceptions:
  #              - com.example.exceptions.BusinessValidationException
  #              - jakarta.persistence.EntityNotFoundException

  circuitbreaker:
    instances:
      inventoryCB:
        failure-rate-threshold: 50
        sliding-window-size: 10
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2

logging:
  level:
    org.hibernate.SQL: debug

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,retries,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always
